### ISSUE TITLE
v5.3rc04 Linux and macOS packages fail to decode

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonBuilds#1]
After several attempts I have not been able to decode ITK v5.3rc04 build archives for Linux. This is echoed in [ITKVkFFTBackend](https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/runs/5821963340?check_suite_focus=true) and [ITKSplitComponents](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/runs/5875068741?check_suite_focus=true) CI.

unzstd fails with warning:

```
...
99 1651M   99 1636M    0     0  35.3M      0  0:00:46  0:00:46 --:--:-- 7003k
 99 1651M   99 1[64](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/runs/5875068812?check_suite_focus=true#step:5:64)4M    0     0  34.7M      0  0:00:47  0:00:47 --:--:-- 7105k
100 1[65](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/runs/5875068812?check_suite_focus=true#step:5:65)1M  100 1651M    0     0  34.1M      0  0:00:48  0:00:48 --:--:-- 7085k
100 1651M  100 1651M    0     0  34.1M      0  0:00:48  0:00:48 --:--:-- [69](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/runs/5875068812?check_suite_focus=true#step:5:69)88k
Error 36 : Decoding error : Frame requires too much memory for decoding 
Extracting files relevant for: cp38
tar: This does not look like a tar archive
tar: ITKPythonPackage/scripts: Not found in archive
tar: Exiting with failure status due to previous errors
...
ERROR: can not find required binary './ITKPythonPackage/scripts/dockcross-manylinux-build-module-wheels.sh'
Error: Process completed with exit code 255.
```

I will also note that v5.3rc04 Linux archives are 0.3GB smaller than the previous release. Maybe something went wrong when compressing the archive for upload?

[v5.3rc04 release](https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04)

[v5.3rc03 release](https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc03)

macOS Python builds appear to fail at the same unzstd decode step with the same error. Windows archives appear to unzip properly.

**Comment by tbirdso** [comment]
@thewtex Are you able to reproduce? And, do you perhaps have the original `.tar` files to try generating new `.std` archives?

**Comment by thewtex** [comment]
We had to improve the compression in the builds to get below the 2.0 GB limit for GitHub releases with 5.3RC4. This patch was used:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/commit/de54e148584827cc3cb89898358510877762f1b7

We may need to modify that approach or how the tarballs are unpacked for successful use in CI.

**Comment by thewtex** [comment]
@tbirdso could you please try uploading the new tarballs here: https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04

and restart the ITKSplitComponents build to verify we have addressed the issue?

**Comment by tbirdso** [comment]
Resolved in https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/190
