### ISSUE TITLE
ITK v5.4rc02 `ITKPythonBuilds-linux-manylinux_2_28` not packaged with Python 3.12 binaries

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKPythonBuilds#2]
## Expected

All v5.4rc02 build archives contain ITK sources and binaries for Python 3.8 - 3.12.

## Observed

At least `ITKPythonBuilds-linux-manylinux_2_28` does not include Python 3.12 sources and binaries as of 2023.11.01.

## Steps to Reproduce

1. Download https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/download/v5.4rc02/ITKPythonBuilds-linux-manylinux_2_28.tar.zst from https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.4rc02
2. Decompress with `unzstd`
3. Verify that other ITK Python sources are present:
```
> tar -tvf ITKPythonBuilds-linux-manylinux_2_28.tar| grep cp3 | wc -l
128840
```
4. Investigate ITK Python 3.12 sources:
```
> tar -tvf ITKPythonBuilds-linux-manylinux_2_28.tar | grep cp312 | wc -l
0
```

**Comment by thewtex** [comment]
With 5.4.0 we have Stable ABI wheels for 3.11 that work with 3.12.
